### ISSUE TITLE
There is some error in the shell scripts

### ISSUE THREAD

**Issue by hpp0hpp** [DHU-Golf/detect#1]
1.  my_env is not a recognized command.
so I mannually activate the venv and keep it runs
2. some path is wrong, you have move the python script under data/tool, but the PS script still refer to under data
3. when I run shell script with cwd is main folder, line like import data.tool.prepare_data as prepare_data
 always raise error cannot import data, but I found data in the folder.

**Comment by hpp0hpp** [comment]
I can help to write document for this repo

**Comment by hpp0hpp** [comment]
@AO-blog Hi, would you mind to help me with a golf move detection project, cut out the clips that only people swinging, and remove the rest part.  I can pay CNY 3000 for this. are you interested, reply or contact me on wechat: hpp0hpp

The raw video is like this: https://v.youku.com/v_show/id_XNTg4MjMyNTM4NA==.html

**Comment by ghost** [comment]
Thank you for your interest in this project. This repo is the example code for the paper Automatic DTW-Based Grading for Golf Swing in Sports. If you just want to  cut out the swing clips, you only need [SwingNet of golfdb](https://github.com/wmcnally/golfdb) or CBAM-SwingNet in this project. 

As for this problem of scripts, you need to add the path to your PYTHONPATH, like this:

> for Windows

`$env:PYTHONPATH="C:/Users/ao/Desktop/detect;$env:PYTHONPATH"`

> for *nix

`export PYTHONPATH="/home/ao/Desktop/detect/":$PYTHONPATH`

As for runninng your own videos, follow the model setting with these two items: `golfdb` and `VideoPose3d`.

If there are no further questions, I will close this issue.
